# Site settings
title: The self-service developer
tag_text: The self-service developer
description: Pursuing awesome developer experiences. You know.. for speed.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
